version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
    reviewers:
      - jhw-db
      - 36b498c8
    assignees:
      - jhw-db
      - 36b498c8
    commit-message:
      prefix: "chore(backend): ‚¨ÜÔ∏è deps"
      prefix-development: "chore(backend): ‚¨ÜÔ∏è dev deps"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    reviewers:
      - jhw-db
      - 36b498c8
    assignees:
      - jhw-db
      - 36b498c8
    commit-message:
      prefix: "chore: üíö ci"
      include: "scope"